### ISSUE TITLE
Override configuration in a separate apt.conf.d file

### ISSUE THREAD

**Issue by colans** [hifis-net/ansible-role-unattended-upgrades#10]
See https://github.com/jnv/ansible-role-unattended-upgrades/issues/32 for details.

Please merge https://github.com/jnv/ansible-role-unattended-upgrades/pull/66, which resolves this by moving the configuration into a new file that doesn't overwrite default settings.

**Comment by Normo** [comment]
Thanks, @colans for creating this issue.

What do you suggest on how to proceed with the exisiting files `/etc/apt/apt.conf.d/20auto-upgrades` and `/etc/apt/apt.conf.d/50unattended-upgrades` ?

**Comment by colans** [comment]
@Normo I handled this in the MR with documentation:
> If you have used an older version of this role, the files `20auto-upgrades` and `50unattended-upgrades` will differ from the system defaults (instead of configuration being placed in a separate file, as we do now). These can be left as-is as they will be overridden. During OS upgrades, when asked if these files should be overwritten by the maintainer's package, say yes. They will then be reset to their default states, and you won't be asked these questions again.
