### ISSUE TITLE
ansible.builtin.import_tasks problem

### ISSUE THREAD

**Issue by huckley** [hifis-net/ansible-role-unattended-upgrades#75]
I write a role which depend on this role and I get:
ERROR! this task 'ansible.builtin.import_tasks' has extra params, which is only allowed in the following modules: win_shell, include_tasks, include_role, group_by, import_tasks, add_host, raw, import_role, script, set_fact, include_vars, shell, meta, include, win_command, command

The error appears to be in '/home/fhackenberger/Dokumente/ansible/rexx.apt/tests/roles/hifis.unattended_upgrades/tasks/main.yml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

I Use ansible 2.9.6
also ansible.builtin.import_task is only available in ansible >= 2.4, but your meta says:
min_ansible_version: "1.4"

**Comment by Normo** [comment]
@huckley Thank you so much for pointing that out!

This role will support all Ansible versions that are officially maintained . So at least version 2.12 should be used.
