### ISSUE TITLE
Added custom of apt-daily timers apt-daily-upgrade

### ISSUE THREAD

**Issue by mabed-fr** [hifis-net/ansible-role-unattended-upgrades#85]
Hello

It seems to me that an important feature is missing.

- The feature of being able to decide when to DOWNLOAD updates ( apt-daily.timer)
- The feature of being able to decide when to INSTALL updates (apt-daily-upgrade.timer)

This happens in the following systemd timers

```
mabed@mabed ~ → systemctl list-timers | grep apt 
Fri 2023-01-20 12:34:48 CET 7min left      Fri 2023-01-20 06:08:39 CET 6h ago       apt-daily.timer              apt-daily.service
Fri 2023-01-20 13:08:27 CET 40min left     Fri 2023-01-20 07:09:38 CET 5h 18min ago apt-daily-upgrade.timer      apt-daily-upgrade.service
```
I don't know their default value because I modify them on my servers

There is no role but an ansible collection that we can add to this role.

*ansible.builtin.systemd

What do you think?

I will start working on the PR

Mathieu

**Comment by mabed-fr** [comment]
My work is ready but I cannot submit PR

**Comment by Normo** [comment]
Thank you @mabed-fr. Is it possible for you to fork the project and submit a PR? If not, what is the error message?

**Comment by mabed-fr** [comment]
Hello,

With pleasure but why forked?

This complicates the contribution can you allow me a PR?

Mabed

**Comment by mabed-fr** [comment]
I don't have time to follow your pipeline, if you want to integrate this essential functionality I'll let you correct the pipeline.

Good for you
