### ISSUE TITLE
apt options are not overridden but merged

### ISSUE THREAD

**Issue by areichhart** [hifis-net/ansible-role-unattended-upgrades#94]
Hello,
thank you for this wonderful Ansible role, especially for the approach of overriding the unattended-upgrades config file instead of replacing it.
Unfortunately, this doesn't work as intended because config options for apt are not overridden but merged. For details see the solution to [this old issue](https://serverfault.com/questions/924538/unattended-upgrades-override-allowed-origins).

Therefore options should be cleared before the override is applied, e.g.
`#clear Unattended-Upgrade::Origins-Pattern;`
should precede the line 
`  Unattended-Upgrade::Origins-Pattern {`

Kind regards

**Comment by Normo** [comment]
Thanks, @areichhart for reporting this!

**Comment by Normo** [comment]
Related to #10
